name: Deploy Web Application

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches:
      - 2-chore-create-cicd-with-github-actions
      - develop
      - 'releases/**'

env:
  BUCKET_NAME: invistus-web-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install and Build
        working-directory: ./web
        run: |
          npm ci
          npm run build

  # deploy_dev:
  # deploy_staging:


  deploy_production:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # AWS Login with OIDC
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.AWS_OIDC_ROLE}}
          role-session-name: github-action-session
          aws-region: ${{ secrets.AWS_REGION }}

    - name: Create or Ignore S3 Bucket
      run: |
        if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>&1; then
          aws s3api create-bucket --bucket $BUCKET_NAME --region${{ secrets.AWS_REGION }}
        else
          echo "Bucket already exists, skipping creation."
        fi

      # Tag S3 bucket for web application 
      - name: Tag S3 Bucket
        run: |
          aws s3api put-bucket-tagging --bucket $BUCKET_NAME --tagging 'TagSet=[{Key=Application,Value=Invistus},{Key=Component,Value=web},{Key=Environment,Value=Test}]'

      # Deploy web pkg to S3 bucket
      - name: Deploy to S3 bucket
        working-directory: ./web
        run: aws s3 sync ./build/ s3://$BUCKET_NAME --delete


