name: Deploy React Frontend to AWS Amplify

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  push:
    branches:
      - develop
      - 2-chore-create-cicd-with-github-actions

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['development', 'staging', 'production']
        include:
          - environment: development
            branch: 2-chore-create-cicd-with-github-actions
            s3_bucket: invistus-web-dev
          # - environment: development
          #   branch: develop
          #   s3_bucket: invistus-web-dev
          - environment: staging
            branch: release/*
            s3_bucket: invistus-web-staging
          - environment: production
            branch: main
            s3_bucket: invistus-web-prod

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install and Build
      working-directory: web
      run: |
        npm ci
        npm run build

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{secrets.AWS_OIDC_ROLE}}
        role-session-name: github-action-session
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Tag S3 Bucket
      run: |
        aws s3api put-bucket-tagging --bucket ${{ matrix.s3_bucket }} --tagging 'TagSet=[{Key=Application,Value=Invistus},{Key=Component,Value=web},{Key=Environment,Value=${{ matrix.environment }}}]'

    - name: Deploy to S3
      working-directory: web
      if: startsWith(github.ref, matrix.branch)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ matrix.s3_bucket }}
        SOURCE_DIR: 'build'


